files:
  include: 'scss/**/*.s+(a|c)ss'
  ignore:
    - 'vendor/**/*.scss'
rules:
  no-mergeable-selectors: 0
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
  nesting-depth:
    - 1
    - max-depth: 3
  class-name-format:
    - 1
    - convention: strictbem