files:
  include: 'src/scss/**/*.s+(a|c)ss'
  ignore:
    - 'src/scss/vendor/**/*.scss'
    - 'src/scss/base/_normalize.scss'
rules:
  no-vendor-prefixes: 0
  no-transition-all: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0
  no-mergeable-selectors: 0
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: true
  nesting-depth:
    - 1
    - max-depth: 3